export const LANGUAGE_MAP: Record<string, string> = {
  ZH: "Mandarin Chinese",
  HI: "Hindi",
  ES: "Spanish",
  FR: "French",
  AR: "Arabic",
  BN: "Bengali",
  PT: "Portuguese",
  RU: "Russian",
  UR: "Urdu",
  AF: "Afrikaans",
  SQ: "Albanian",
  AM: "Amharic",
  HY: "Armenian",
  AZ: "Azerbaijani",
  EU: "Basque",
  BE: "Belarusian",
  BS: "Bosnian",
  BG: "Bulgarian",
  MY: "Burmese",
  CA: "Catalan",
  HR: "Croatian",
  CS: "Czech",
  DA: "Danish",
  NL: "Dutch",
  ET: "Estonian",
  TL: "Filipino/Tagalog",
  FI: "Finnish",
  GL: "Galician",
  KA: "Georgian",
  DE: "German",
  EL: "Greek",
  GU: "Gujarati",
  HT: "Haitian Creole",
  HA: "Hausa",
  HE: "Hebrew",
  HU: "Hungarian",
  IS: "Icelandic",
  IG: "Igbo",
  ID: "Indonesian",
  GA: "Irish",
  IT: "Italian",
  JA: "Japanese",
  JV: "Javanese",
  KN: "Kannada",
  KK: "Kazakh",
  KM: "Khmer",
  KO: "Korean",
  KU: "Kurdish",
  KY: "Kyrgyz",
  LO: "Lao",
  LV: "Latvian",
  LT: "Lithuanian",
  MK: "Macedonian",
  MS: "Malay",
  ML: "Malayalam",
  MT: "Maltese",
  MR: "Marathi",
  MN: "Mongolian",
  NE: "Nepali",
  NO: "Norwegian",
  OR: "Odia",
  PS: "Pashto",
  FA: "Persian/Farsi",
  PL: "Polish",
  PA: "Punjabi",
  RO: "Romanian",
  SR: "Serbian",
  SD: "Sindhi",
  SI: "Sinhala",
  SK: "Slovak",
  SL: "Slovenian",
  SO: "Somali",
  SW: "Swahili",
  SV: "Swedish",
  TG: "Tajik",
  TA: "Tamil",
  TE: "Telugu",
  TH: "Thai",
  TR: "Turkish",
  TK: "Turkmen",
  UK: "Ukrainian",
  UZ: "Uzbek",
  VI: "Vietnamese",
  CY: "Welsh",
  XH: "Xhosa",
  YO: "Yoruba",
  ZU: "Zulu",
};

/** Returns the full language name for a code, or the code itself as fallback. */
export function langName(code: string): string {
  return LANGUAGE_MAP[code.toUpperCase()] ?? code;
}
