#!/usr/bin/env bash
# dev-sandbox.sh — snapshot prod data into a local gmi_dev database.
# Run once per dev session (or whenever you want fresh prod data).
# The local DB is completely isolated — writes never reach Supabase.
set -euo pipefail

# ── Paths ──────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# When called from a worktree, REPO_ROOT is the worktree dir.
# We always want the main repo root (where .env.local lives).
MAIN_ROOT=$(git -C "$REPO_ROOT" worktree list --porcelain 2>/dev/null \
  | grep "^worktree" | head -1 | awk '{print $2}')
MAIN_ROOT="${MAIN_ROOT:-$REPO_ROOT}"

ENV_FILE="${MAIN_ROOT}/.env.local"
[[ -f "$ENV_FILE" ]] || ENV_FILE="${MAIN_ROOT}/.env"
[[ -f "$ENV_FILE" ]] || { echo "ERROR: no .env.local found at $MAIN_ROOT"; exit 1; }

LOCAL_DB="gmi_dev"
LOCAL_USER="$(whoami)"
LOCAL_URL="postgresql://${LOCAL_USER}@localhost/${LOCAL_DB}"

# ── 1. Start local Postgres ────────────────────────────────────────────────────
echo "→ Starting PostgreSQL 14..."
PG_DATA="/opt/homebrew/var/postgresql@14"
PG_CTL="/opt/homebrew/opt/postgresql@14/bin/pg_ctl"
PID_FILE="${PG_DATA}/postmaster.pid"

# Clean up stale PID file if the recorded PID isn't actually postgres
if [[ -f "$PID_FILE" ]]; then
  STORED_PID=$(head -1 "$PID_FILE")
  if ! ps -p "$STORED_PID" -o comm= 2>/dev/null | grep -q postgres; then
    echo "  Removing stale PID file (PID $STORED_PID is not postgres)..."
    rm -f "$PID_FILE"
  fi
fi

"$PG_CTL" -D "$PG_DATA" status &>/dev/null || "$PG_CTL" -D "$PG_DATA" start -l "${PG_DATA}/postgresql.log" 2>&1 | tail -2

# Wait up to 10 s for it to be ready
for i in {1..10}; do
  pg_isready -h localhost -q && break
  sleep 1
done
pg_isready -h localhost -q || { echo "ERROR: local Postgres did not start"; exit 1; }
echo "  Ready."

# ── 2. Create local database ───────────────────────────────────────────────────
echo "→ Creating local database '${LOCAL_DB}'..."
createdb "$LOCAL_DB" 2>/dev/null && echo "  Created." || echo "  Already exists (will be repopulated)."

# ── 3. Write .env.development.local (overrides DATABASE_URL for 'next dev') ───
DEV_ENV="${REPO_ROOT}/.env.development.local"
cat > "$DEV_ENV" <<EOF
# Auto-generated by scripts/dev-sandbox.sh — do not commit
DATABASE_URL=${LOCAL_URL}
DIRECT_URL=${LOCAL_URL}
NEXTAUTH_URL=http://localhost:3000
EOF
echo "→ Wrote ${DEV_ENV}"

# ── 4. Push Prisma schema to local DB ─────────────────────────────────────────
echo "→ Syncing Prisma schema to local DB..."
cd "$REPO_ROOT"
DATABASE_URL="$LOCAL_URL" DIRECT_URL="$LOCAL_URL" \
  npx prisma db push --skip-generate --accept-data-loss 2>&1 | tail -3
echo "  Schema up to date."

# ── 5. Get production connection URL ─────────────────────────────────────────
# Prefer DIRECT_URL (bypasses connection pooler — required for pg_dump).
# Search both .env.local and .env since the URL may be in either.
extract_url() {
  local key="$1"
  for f in "${MAIN_ROOT}/.env.local" "${MAIN_ROOT}/.env"; do
    [[ -f "$f" ]] || continue
    local val
    val=$(grep -E "^${key}=" "$f" 2>/dev/null | head -1 | cut -d'=' -f2- | tr -d '"' | tr -d "'" | xargs)
    [[ -n "$val" ]] && { echo "$val"; return; }
  done
}

PROD_URL=$(extract_url "DIRECT_URL")
[[ -z "$PROD_URL" ]] && PROD_URL=$(extract_url "DATABASE_URL")
[[ -z "$PROD_URL" ]] && { echo "ERROR: DATABASE_URL not found in .env or .env.local"; exit 1; }

# ── 6 & 7. Copy production data via psql \COPY (version-independent) ─────────
echo "→ Copying production data table by table (may take 20–60 s)..."

# Get ordered list of tables (skip Prisma internals)
TABLES=$(psql "$PROD_URL" -t -A -c "
  SELECT tablename FROM pg_tables
  WHERE schemaname = 'public'
    AND tablename NOT LIKE '\\_prisma%'
  ORDER BY tablename
" 2>/dev/null)

# Disable FK triggers on local so we can insert in any order
psql "$LOCAL_URL" -q -c "SET session_replication_role = replica;" 2>/dev/null || true

# Truncate all local tables first (cascade)
psql "$LOCAL_URL" -q -c "
  DO \$\$ DECLARE r RECORD;
  BEGIN
    FOR r IN SELECT tablename FROM pg_tables
             WHERE schemaname = 'public'
               AND tablename NOT LIKE '\\_prisma%'
    LOOP
      EXECUTE 'TRUNCATE TABLE \"' || r.tablename || '\" CASCADE';
    END LOOP;
  END \$\$;
" 2>/dev/null || true

# Copy each table prod → local using explicit column order from LOCAL schema
COPIED=0
SKIPPED=0
TMPFILE="/tmp/gmi_table_copy.tsv"

while IFS= read -r table; do
  [[ -z "$table" ]] && continue

  # Get column list from LOCAL table (Prisma's canonical order)
  COLS=$(psql "$LOCAL_URL" -t -A -c "
    SELECT string_agg('\"' || column_name || '\"', ',' ORDER BY ordinal_position)
    FROM information_schema.columns
    WHERE table_name = '${table}' AND table_schema = 'public'
  " 2>/dev/null | tr -d '[:space:]')
  [[ -z "$COLS" ]] && continue

  # Dump from prod to temp file
  if ! psql "$PROD_URL" -c "\COPY \"${table}\" (${COLS}) TO '${TMPFILE}'" 2>/dev/null; then
    echo "  Warning: could not export ${table} from prod"
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  # Skip if empty
  [[ ! -s "$TMPFILE" ]] && { SKIPPED=$((SKIPPED + 1)); continue; }

  # Restore to local — disable FK checks within the same session
  if psql "$LOCAL_URL" -q 2>/dev/null <<PSQL
SET session_replication_role = replica;
\COPY "${table}" (${COLS}) FROM '${TMPFILE}'
SET session_replication_role = DEFAULT;
PSQL
  then
    COPIED=$((COPIED + 1))
  else
    echo "  Warning: could not import ${table} to local"
    SKIPPED=$((SKIPPED + 1))
  fi
done <<< "$TABLES"

rm -f "$TMPFILE"

# Re-enable FK triggers
psql "$LOCAL_URL" -q -c "SET session_replication_role = DEFAULT;" 2>/dev/null || true

echo "  Copied ${COPIED} tables, skipped ${SKIPPED} empty/errored."

# ── 8. Seed dev users into local DB ──────────────────────────────────────────
echo "→ Seeding dev users..."
psql "$LOCAL_URL" -q <<'PSQL'
-- Dev admin (maps to dev toolbar "Admin" button)
INSERT INTO "User" (id, email, name, role, roles, status, "onboardingComplete", "createdAt")
VALUES (
  'dev-ADMIN-user-id',
  'dev-admin@dev.local',
  'Dev Admin',
  'ADMIN',
  ARRAY['ADMIN','DEV'],
  'ACTIVE',
  true,
  NOW()
) ON CONFLICT (email) DO UPDATE SET role='ADMIN', roles=ARRAY['ADMIN','DEV'], status='ACTIVE';

-- Dev volunteer (maps to "Volunteer" button)
INSERT INTO "User" (id, email, name, role, roles, status, "onboardingComplete", "createdAt")
VALUES (
  'dev-VOLUNTEER-user-id',
  'dev-volunteer@dev.local',
  'Dev Volunteer',
  'VOLUNTEER',
  ARRAY['VOLUNTEER'],
  'ACTIVE',
  true,
  NOW()
) ON CONFLICT (email) DO UPDATE SET role='VOLUNTEER', roles=ARRAY['VOLUNTEER'], status='ACTIVE';

INSERT INTO "VolunteerProfile" (id, "userId", languages, "isCleared", "createdAt")
VALUES (
  'dev-VOLUNTEER-profile-id',
  'dev-VOLUNTEER-user-id',
  ARRAY[]::text[],
  false,
  NOW()
) ON CONFLICT ("userId") DO NOTHING;

-- Dev instructor (maps to "Instructor" button)
INSERT INTO "User" (id, email, name, role, roles, status, "onboardingComplete", "createdAt")
VALUES (
  'dev-INSTRUCTOR-user-id',
  'dev-instructor@dev.local',
  'Dev Instructor',
  'INSTRUCTOR',
  ARRAY['INSTRUCTOR'],
  'ACTIVE',
  true,
  NOW()
) ON CONFLICT (email) DO UPDATE SET role='INSTRUCTOR', roles=ARRAY['INSTRUCTOR'], status='ACTIVE';

INSERT INTO "VolunteerProfile" (id, "userId", languages, "isCleared", "createdAt")
VALUES (
  'dev-INSTRUCTOR-profile-id',
  'dev-INSTRUCTOR-user-id',
  ARRAY[]::text[],
  false,
  NOW()
) ON CONFLICT ("userId") DO NOTHING;
PSQL
echo "  Dev users ready."

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "✓ Dev sandbox ready."
echo "  Local DB : $LOCAL_URL"
echo "  Next run : npm run dev  (in the worktree directory)"
echo ""
echo "  Toolbar buttons now work: Admin / Volunteer / Instructor"
echo "  All writes stay local — production is untouched."
